### ISSUE TITLE
Can extra classes be provided?

### ISSUE THREAD

**Issue by Alexbeast-CN** [SysCV/shift-dev#11]
I noticed in your paper that there are six categories of traffic participants for 2d object detection. But will other things like traffic lights and traffic signs classes be provided for object detection task?

**Comment by suniique** [comment]
Hey @Alexbeast-CN! Our dataset has semantic labels for traffic lights and signs that can be used for 2D semantic segmentation (see https://www.vis.xyz/shift/get_started/). However, providing them with 2D/3D bounding boxes is not supported currently. We will label this as a future enhancement!
