### ISSUE TITLE
Continuous Shift  'timeofday_fine' Double Checking

### ISSUE THREAD

**Issue by M-A-Hassan** [SysCV/shift-dev#15]
Can someone review the 100x continuous shift det_2d annotations, specifically the 'timeofday_fine'? 
As shown in the case below, the time of the day seems to be off. 
Thanks

![download (11)](https://user-images.githubusercontent.com/83038862/186417279-4bcdfe4c-5d4b-413c-975b-33e8b35e300a.png)

**Comment by suniique** [comment]
Hey @M-A-Hassan, thanks for the question! These fields (time of day and weather) are used for discrete domain shifts. For continuous parts, they only mean the start condition of domain shift. We are working on releasing a sequence info label to make extracting the domain info for the frames in the middle easier. It will probably be done next week.

**Comment by M-A-Hassan** [comment]
Thanks @suniique

**Comment by suniique** [comment]
Hey @M-A-Hassan, we have updated all label files (e.g., det_2d) of continuous shifts that store all environment parameters. Also, we have added new sequence info files (.csv) which summarize the beginning and end conditions per sequence. Hope this will make things easier. 
Descriptions are here https://www.vis.xyz/shift/get_started (Label details/sequence information).
