### ISSUE TITLE
Can the semantic labels tranfer to the 19 classes in cityscapes dataset? 

### ISSUE THREAD

**Issue by ywher** [SysCV/shift-dev#16]
Hi, nice work and I think it is valuable. 
I wonder if the semantic labels for semantic segmentation can be tranferred to the 19 classes in cityscapes.
Right now there are only 13 classes consistent with the cityscapes dataset. They are raod, sidewalk, building, wall, fence, pole, traffic light, traffic sign, vegetation, terrain, sky, pedestrian, and vehicle.
However, the rider, truck, bus, train, motorcycle and bicycle are not labeled in shift.
The labels are not consistent between so i can not conduct domain adaptation experiments from shift to cityscapes.  Thanks.

**Comment by mattiasegu** [comment]
Hi @ywher, we actually provide information on the mapping between SHIFT categories and Cityscapes categories in our [Get Started](https://www.vis.xyz/shift/get_started/) page under the "Annotations/Segmentation labels" section. You can also refer to our reply to #23.

Hope this helps!
