### ISSUE TITLE
this dataset  for point cloud unsupervied domain adaptation semantic segmentation?

### ISSUE THREAD

**Issue by shuchao97** [SysCV/shift-dev#20]
hello author, thanks to your great work. I want to know that if the dataset can be used for point cloud unsupervised domain adaption semantic segmentation research. it's important for me, thanks again.@mattiasegu @fyu@suniique

**Comment by suniique** [comment]
Hey @shuchao97, thanks for your interest in SHIFT! 

If I understand your question correctly, you are looking for point cloud data with domain changes. If so, we are sorry to tell you that the LiDAR data in our dataset are not sensitive to domain shift (e.g., rain, fog, …), as the CARLA LiDAR simulation is not affected by different weather conditions. However, one of our plans is to include physics-based models for LiDAR simulation under different weather. Let's keep in touch!

**Comment by jeromepatel** [comment]
@suniique Thank you for the great dataset, I am working on a similar weather shift task (both with Carla simulator and without Carla) and would like to know whether there's some progress from your side ? Would be happy to collaborate on this as well!
Also, as a side question, is there any possibility to get my hands on the code for generating SHIFT dataset ?
