### ISSUE TITLE
how to project point cloud to pixel plane of front image 

### ISSUE THREAD

**Issue by shuchao97** [SysCV/shift-dev#26]
hello author, thanks to your great work. In this dataset, My work carried out converts the point cloud data in the lidar coordinate system to the pixel plane of the camera, and at the same time obtains the corresponding pixel coordinates. First, through the transformation matrix from lidar to camera coordinate system, the point cloud in the lidar coordinate system is converted into the point in the camera coordinate system, and then the camera's internal parameter matrix is used to convert the point of the camera coordinate system to the pixel plane. Finally, the pixel coordinates of the point cloud are only kept in the range of (800, 1280).
lidar to camera coordinate system matrix Tl=[1,0,0,-0.5;0,1,0,0;0,0,1,1.6], it is according to rotation=[0, 0, 0], translation = [0.5, 0, 1.6] in sensors.yaml file. 
camera intrinsic matrix Tc = [640, 0, 640; 0, 640, 400; 0, 0, 1], according to their intrinsic parameters are (center_x, center_y) = (640, 400), (focal_x, focal_y) = (640, 640), skew = 0.
pixel coordinate = Tc*Tl*point cloud coordinate
but in above process, i can't project point cloud to according true pixel plane of front view, so  i want to know if i use the false Tl or Tc matrix, or there are something else factors that i have not considered. 
thanks again. @suniique @fyu @mattiasegu

**Comment by palmdong** [comment]
@shuchao97 hellow, have you successfully done the 3d-to-2d projection?
