### ISSUE TITLE
Camera gt pose

### ISSUE THREAD

**Issue by DoongLi** [SysCV/shift-dev#29]
Do the dataset provide the real value of the camera pose?

**Comment by suniique** [comment]
Hey @DoongLi, have you referred to this issue https://github.com/SysCV/shift-dev/issues/6 and the code [shift_dev/vis/sensor_pose.py](https://github.com/SysCV/shift-dev/blob/main/shift_dev/vis/sensor_pose.py) which visualizes the camera poses? Please tell me if the problems consist!

**Comment by DoongLi** [comment]
I'll give it a try，and I'm trying to run a vSLAM method on this dataset
