### ISSUE TITLE
Does "Sequence" stand for something? (Question about folder names)

### ISSUE THREAD

**Issue by jacob-kang** [SysCV/shift-dev#32]
Hi.
Thanks for your great job.

I'm currently using Cityscapes and Shift for semantic segmentation.
As you know, Shift has a lot of data, then the training time is longer than others. 
And It can not be compared fairly with other datasets because Shift has more numerous datasets.

So I'm picking a few folders which can alternate the whole folders (Due to time-consuming)
But The folder names are f59b-1e66, f520-eb10, etc.
I found these come from the sequence.

Does the sequence stand for something special? For example, ffxx-xxxx means... Few people in the scene...
If there is no rule naming the folder, I will pick a few folders randomly.

Thanks.

**Comment by jacob-kang** [comment]
Solved by myself. Found csv file.

**Comment by twangnh** [comment]
hi, could you let me know where to download the csv file
