### ISSUE TITLE
How to download the night data only?

### ISSUE THREAD

**Issue by xukuanHIT** [SysCV/shift-dev#5]
Hi, thank you for the great dataset. I find the dataset includes the night data on the homepage, may I know how to download the dataset at night or dusk only?

**Comment by mattiasegu** [comment]
Hi @xukuanHIT, I'm glad you like our work! 

Yes, it is correct that our dataset includes night sequences. However, it is not possible to download night sequences **only**. To allow that we would have to split the folders into e.g. `daytime`, `dawn/dusk`, `night`, `cloudy`, `rainy`, ... Unfortunately, this is not possible as our domain shifts happen along different directions (time of day, rain strength, fog strength, cloudiness, ..." and  some e.g. `night` sequences can also be collected in `rainy` conditions. Such a folder structure would thus create some duplicate sequences across the different domain folders.

We thus recommend you to download the dataset with the view that you would like to use, e.g. front view, and the annotations that you would like to use, e.g. 2D object detection. The file [discrete/images/val/front/det_2d.json](https://dl.cv.ethz.ch/shift/discrete/images/val/front/det_2d.json) would then contain the annotations stored in the Scalabel format. As such, you can then filter every sequence and frame based on their `attributes` field -which contains the weather parameters - and use the night sequences only.

Moreover, to facilitate ease of use we will also provide a json file containing only the weather parameters for each sequence.

Please let me know if you have any follow-up questions :)

**Comment by xukuanHIT** [comment]
OK, thanks a lot. I will have a try.
