### ISSUE TITLE
Data license

### ISSUE THREAD

**Issue by zshn25** [SysCV/shift-dev#51]
Greetings,

Does `LICENSE` file refer to the repo license or the data license or both? If the first, what is the license of the data?

**Comment by zshn25** [comment]
Ok, I see a [CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) license on your [webpage](https://www.vis.xyz/shift/). Please correct me if I'm wrong but I assume that's for the dataset and not the webpage.

**Comment by fyu** [comment]
Your understanding is right.
