### ISSUE TITLE
Are the codes for TTA available?

### ISSUE THREAD

**Issue by Cascol-SCUT** [SysCV/shift-dev#57]
It would be of great help, please let me know if you can share the code

**Comment by suniique** [comment]
Hey @Cascol-SCUT, thanks for the question!

Yes, we do have a repo working with the TTA on the SHIFT dataset. Feel free to check it out at [Continuous_Test_Time_Adaptation](https://github.com/zwbx/SHIFT-Continuous_Test_Time_Adaptation). You can ask for more information there.

**Comment by mattiasegu** [comment]
Hi @Cascol-SCUT, we also provide a codebase for test-time adaptation of object detection.

You can find it here: https://github.com/SysCV/shift-detection-tta

**Comment by Cascol-Chen** [comment]
> Hey @Cascol-SCUT, thanks for the question!
> 
> Yes, we do have a repo working with the TTA on the SHIFT dataset. Feel free to check it out at https://github.com/zwbx/SHIFT-Continuous_Test_Time_Adaptation. You can ask for more information there!
> 
> Also, we are organizing challenges based on SHIFT in the [VCL Workshop](https://wvcl.vis.xyz/challenges) at ICCV2023. The TTA is also part of the challenges; welcome to participate!

Thanks for your kind reply. Interestingly, I find that Tent does not improve performance compared with source model, which contradicts to the paper in Figure 6. Could you further explain the difference?
