### ISSUE TITLE
Sort according to domains/weathers?

### ISSUE THREAD

**Issue by waychin-weiqin** [SysCV/shift-dev#7]
Hi, thank you for releasing the dataset. I am just wondering if it is possible to sort the provided dataset according to the domains or weather? For instance 

```
- Root 
- - Rain
- - - all images with rainy weather
- - Cloud
- - - all images with cloudy weather
- - Fog
- - - all images with foggy weather
- - Night
- - - all images with nighttime weather
```

Thank you :)

**Comment by waychin-weiqin** [comment]
I figured it out.

**Comment by mattiasegu** [comment]
Hi @waychin-weiqin, I'm glad you like our work and were able to figure out the issue! I will leave a reply here for future reference.

As you probably already found out, we recommend you to download the dataset with the view that you would like to use, e.g. front view, and the annotations that you would like to use, e.g. 2D object detection. The file [discrete/images/val/front/det_2d.json](https://dl.cv.ethz.ch/shift/discrete/images/val/front/det_2d.json) would then contain the annotations stored in the Scalabel format. As such, you can then filter every sequence and frame based on their attributes field -which contains the weather parameters - and use the e.g. night sequences only.

Regarding the folder split that you recommended, unfortunately this is not possible as our domain shifts happen along different directions (time of day, rain strength, fog strength, cloudiness, ..." and some e.g. night sequences can also be collected in rainy conditions. Such a folder structure would thus create some duplicate sequences across the different domain folders.

To facilitate ease of use and to make it easier to find out the domain division, we will also provide a json file containing only the weather parameters for each sequence.

Please let me know if you have any follow-up questions :)

**Comment by waychin-weiqin** [comment]
Hi @mattiasegu, thank you for the info! That is exactly where I sorted all the images according to their attributes. However, I found that there is a slight mismatch between what is stored in the det_2d.json and what is currently mentioned on the official webpage. For example, I found the following attributes in the json file:

1. timeofday
2. timeofday_fine
3. weather
4. weather_fine
5. town 

However, on the official website [[page](https://www.vis.xyz/shift/get_started/)], it is mentioned that the following attributes are stored in the json file:

1. timeofday
2. weather
3. vehicle_density
4. pedestrian_density
5. scene

It is not really a big deal, but I thought it is worth pointing it out :)

**Comment by mattiasegu** [comment]
That's right, thanks for pointing it out! We will fix that soon. The timeofday_fine and weather_fine attributes report domain parameters at a finer level, e.g. the azimuth angle of the sun. We will clarify this in the documentation.
